// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: search.proto

package go_micro_service_search

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SearchService service

type SearchService interface {
	//存储文件信息
	SaveDocument(ctx context.Context, in *ReqSaveDocument, opts ...client.CallOption) (*RespSaveDocument, error)
}

type searchService struct {
	c    client.Client
	name string
}

func NewSearchService(name string, c client.Client) SearchService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.search"
	}
	return &searchService{
		c:    c,
		name: name,
	}
}

func (c *searchService) SaveDocument(ctx context.Context, in *ReqSaveDocument, opts ...client.CallOption) (*RespSaveDocument, error) {
	req := c.c.NewRequest(c.name, "SearchService.SaveDocument", in)
	out := new(RespSaveDocument)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchService service

type SearchServiceHandler interface {
	//存储文件信息
	SaveDocument(context.Context, *ReqSaveDocument, *RespSaveDocument) error
}

func RegisterSearchServiceHandler(s server.Server, hdlr SearchServiceHandler, opts ...server.HandlerOption) error {
	type searchService interface {
		SaveDocument(ctx context.Context, in *ReqSaveDocument, out *RespSaveDocument) error
	}
	type SearchService struct {
		searchService
	}
	h := &searchServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SearchService{h}, opts...))
}

type searchServiceHandler struct {
	SearchServiceHandler
}

func (h *searchServiceHandler) SaveDocument(ctx context.Context, in *ReqSaveDocument, out *RespSaveDocument) error {
	return h.SearchServiceHandler.SaveDocument(ctx, in, out)
}
